<root>:
    orientation: "vertical"
    BoxLayout:
        size_hint: 1, .04
        background_color: 1, 1, 1, 1
    BoxLayout:
        size_hint: 1, .1
        orientation: "horizontal"
        Image:
            source: ""
            size_hint: .25, 1
        Button:
            text: "Home"
        Button:
            text: "Passwords"
        Button:
            text: "Help"
    Label:
        text: "hello World!"
        bold: True
        font_size: '24sp'
        color: 1, 0, 0, 1